# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongotest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secure
    ports:
      - 27017:27017
    volumes:
      - /Users/thanachantrapong/mongodb/data/db:/data/db